### ISSUE TITLE
pitometer grading showing missing violations data and incorrect metricscore

### ISSUE THREAD

**Issue by robertjahn** [keptn/pitometer-grader-thresholds#3]
**Describe the bug**
pitometer grading showing missing violations data and incorrect metricscore

**To Reproduce**
Passing in a perfspec file cofigured with threasholds

**Expected behavior**
indicator results with proper metrics score and violations detail

**Screenshots**
Here are a few examples:

Missing violations
![image](https://user-images.githubusercontent.com/24907089/56512344-172f7380-64fd-11e9-9dbe-34cfdb80a2b2.png)

Got a upper severe but got 50% of score
![image](https://user-images.githubusercontent.com/24907089/56512360-1e568180-64fd-11e9-8732-bdb7c67d141b.png)

Both have upper severe but 2nd once got a score
![image](https://user-images.githubusercontent.com/24907089/56512390-329a7e80-64fd-11e9-9320-5cd7c9a8d608.png)

**Environment**
https://github.com/keptn/pitometer/tree/0.0.2

**Additional context**
Using modules as part of https://github.com/dt-demos/pitometer-web-service

**Comment by robertjahn** [comment]
I am also seeing strange results for time ranges.  If I pass in this ```{
	"timeStart": 1555891200 .  (prior day),
	"timeEnd":   1556061466,
,```

I will get results ok.  But is I pass in this a start time this is only 5 minutes earlier....
```
	"timeStart": 1556061161,
	"timeEnd":   1556061466,   (or even 1556060400  17 min earlier)
````
I get missing results
```
{
    "totalScore": 100,
    "objectives": {
        "pass": 200,
        "warning": 150
    },
    "indicatorResults": [
        {
            "id": "P90_ResponseTime",
            "violations": [],
            "score": 20
        },
        {
            "id": "AVG_ResponseTime",
            "violations": [],
            "score": 80
        }
    ],
    "result": "fail"
}
```

**Comment by danielkhan** [comment]
Please provide the full perfspec and the result. The screenshots are hard to read.
Additionally, what do you mean with "missing results"?
Also, please create one issue per problem.

**Comment by robertjahn** [comment]
I have re-tested the update in 0.0.2.  The upperWarning is now showing up properly for that scenario.  As to my observation on "violations": [], that was my misunderstand if the output. So no issue with that.
